version: '3.8'
services:
  backend:
    build: ./backend
    ports:
      - '5000:5000'
    env_file:
      - ./backend/.env
    volumes:
      - ./backend/src:/app/src

  frontend:
    build: ./frontend
    ports:
      - '3000:3000'
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
    depends_on:
      - backend